### PR TITLE
Population MCMC notebook

### LINKED ISSUE #19: Create notebook for population mcmc

### PR DESCRIPTION
**Pull request by MichaelClerx**
See #19 

Needs a few pints PRs to be merged before it can run:

- [x] https://github.com/pints-team/pints/pull/1383
- [x] https://github.com/pints-team/pints/pull/1384
- [x] https://github.com/pints-team/pints/pull/1385

### CODE REVIEW

**Comment by MichaelClerx** [comment]
This one's now ready for review!

**Review by ben18785 — CHANGES_REQUESTED** [review]
Thanks @MichaelClerx -- looks great! A few smallish comments:

- "This might expected:" -> "This might be expected:"
- I'd remove the banana problem as most methods struggle on this

**Comment by MichaelClerx** [comment]
Thanks @ben18785 . Done!

**Comment by MichaelClerx** [comment]
@ben18785 can you hit the approve button so I can merge?

**Review by ben18785 — APPROVED** [review]

**Pull request merged**
